name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          👋 Hi there! Thank you for opening your first issue on **Smart Scraper**! 
          
          We appreciate you taking the time to contribute to our project. Feel free to provide as much detail as possible to help us understand and resolve the issue. If you have any questions, don't hesitate to ask!

        pr-message: |
          🎉 Thank you for submitting your first pull request to **Smart Scraper**! 

          We’re thrilled to have you contribute. Your efforts are greatly appreciated, and we’ll review your PR as soon as possible. If there are any updates or questions, we'll let you know. Welcome aboard, and happy coding!
