# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale

name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (UTC)

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale due to inactivity. If no further activity occurs, it will be closed.'
        stale-pr-message: 'This pull request has been marked as stale due to inactivity. If no further activity occurs, it will be closed.'
        days-before-stale: 30  # Number of days before an issue or PR is marked stale
        days-before-close: 7   # Number of days to wait before closing a stale issue or PR
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
